print("Bem vindo a loja de gelados do Gabriel Fontoura")
print("-" * 20, "Cardápio", "-" *21 )
print("-" * 51 )
print("---|  Tamanho  |  Cupuaçu (CP)  |  Açaí (AC)   |---") 
print("---|     P     |    R$  9.00    |  R$ 11.00    |---") 
print("---|     M     |    R$ 14.00    |  R$ 16.00    |---") 
print("---|     G     |    R$ 18.00    |  R$ 20.00    |---") 
print("-" * 51 )
# sabor = input("Entre com o sabor desejado (CP/AC): ").lower()
# tamanho = input("Entre com o tamanho desejado (P/M/G): ")